# Generated by Django 5.1.1 on 2024-10-08 18:07

import django.core.validators
import django.db.models.deletion
import projects_tool.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, unique=True)),
                ('description', models.CharField(blank=True, max_length=256)),
                ('imageField', models.ImageField(blank=True, upload_to='media/')),
                ('slugField', models.SlugField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('position', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects_tool.board')),
            ],
            options={
                'unique_together': {('board', 'title')},
            },
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('colour', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator('^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')])),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects_tool.project')),
            ],
            options={
                'unique_together': {('title', 'project')},
            },
        ),
        migrations.AddField(
            model_name='board',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects_tool.project'),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_no', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=64)),
                ('description', models.CharField(blank=True, max_length=512)),
                ('priority', models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='MEDIUM', max_length=6)),
                ('story_points', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100), projects_tool.models.divisible_by_five])),
                ('labels', models.ManyToManyField(to='projects_tool.label')),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects_tool.list')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='board',
            unique_together={('project', 'title')},
        ),
    ]
